### ISSUE TITLE
Merge initial specs with master/hydro-devel

### ISSUE THREAD

**Issue by bit-pirate** [osrf/std_capabilities#2]
With a first implementation for TB soon in place, I'd like to get our initial set of specs merge with the main development branch (e.g. hydro-devel) and released.

I'll report back, when the TB changes are in place.

**Comment by bit-pirate** [comment]
@wjwwood can you merge the branches today or tomorrow or is there more work involved I'm not aware of?

**Comment by wjwwood** [comment]
Done.

**Comment by bit-pirate** [comment]
Thank you, sir! :bow:
