### ISSUE TITLE
Release into hydro and indigo

### ISSUE THREAD

**Issue by bit-pirate** [osrf/std_capabilities#3]
Now that capabilities have been released (https://github.com/osrf/capabilities/issues/61), it would be great to have this released as well.

**Comment by wjwwood** [comment]
Similar to `rqt_capabilities`, would you rather a preliminary release of this (before review) with the understanding that it may change after review or would you like to wait until we have iterated with the community on it? Not sure when I'll get around to that.

**Comment by bit-pirate** [comment]
I would do a release before reaching out to the community. This would make it a bit easier to develop on top of it and more importantly will make it easier for interested users to try it out.

The upcoming demo(s) will keep us busy for a few more weeks. So it will be another month or two to prepare everything for proper announcement.

I'd like to do an early release of the std_capabilities soonish and do another after the TB apps have been changed to use capabilities.

If you are too busy to do the release at the moment, then I could do it as well - would need access to this and the release repo though.

**Comment by wjwwood** [comment]
Ok, I have released for Groovy, Hydro, and Indigo.

**Comment by bit-pirate** [comment]
Great, thanks!

**Comment by dirk-thomas** [comment]
`rqt_common_plugins` is finally released into _Indigo_.

**Comment by wjwwood** [comment]
I think this was meant for https://github.com/osrf/rqt_capabilities/issues/9, but thanks anyways :stuck_out_tongue: 

I'll make sure to release that now.

**Comment by bit-pirate** [comment]
> rqt_common_plugins is finally released into Indigo.

:dancer: Sweeeet. Finally! :yum:
